name: Apple Music ALAC Downloader

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行
  workflow_dispatch:
    inputs:
      album_url:
        description: 'Apple Music Album URL (e.g. https://music.apple.com/album/123456789)'
        required: true

env:
  ANDROID_HOME: /home/runner/Android
  FRIDA_VERSION: "16.0.8"
  ADB_INSTALL_TIMEOUT: "120"  # 延长ADB安装超时时间(秒)

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget unzip openjdk-17-jdk \
            python3-pip qemu-kvm libvirt-daemon-system git golang
          sudo usermod -aG kvm $USER
          sudo chmod 777 /dev/kvm

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android components
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "ndk;25.2.9519653"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-33;google_apis;x86_64"
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n "AppleMusicAVD" -k "system-images;android-33;google_apis;x86_64" -d pixel_4 --force

      - name: Install Frida tools
        run: pip3 install frida-tools

  download-music:
    needs: setup-environment
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone alacleaker/downloader
        run: |
          git clone --depth 1 https://github.com/alacleaker/apple-music-alac-downloader.git
          cd apple-music-alac-downloader
          git submodule update --init --recursive

      - name: Start emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd AppleMusicAVD -writable-system -no-snapshot-load -no-audio -no-window -gpu swiftshader_indirect &
          $ANDROID_HOME/platform-tools/adb wait-for-device
          while [ "$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
            sleep 5
            echo "Waiting for emulator boot..."
          done
          $ANDROID_HOME/platform-tools/adb root
          $ANDROID_HOME/platform-tools/adb remount

      - name: Install Apple Music APK
        run: |
          wget https://storage.googleapis.com/apple-music-apk/applemusic.apk -O apple-music-alac-downloader/apple-music.apk
          $ANDROID_HOME/platform-tools/adb install -t -g apple-music-alac-downloader/apple-music.apk
          $ANDROID_HOME/platform-tools/adb shell am start -n com.apple.android.music/com.apple.android.music.MainActivity
          sleep 15

      - name: Setup Frida server
        run: |
          wget https://github.com/frida/frida/releases/download/$FRIDA_VERSION/frida-server-$FRIDA_VERSION-android-x86.xz
          unxz frida-server-$FRIDA_VERSION-android-x86.xz
          $ANDROID_HOME/platform-tools/adb push frida-server-$FRIDA_VERSION-android-x86 /data/local/tmp/frida-server
          $ANDROID_HOME/platform-tools/adb shell "chmod 755 /data/local/tmp/frida-server"
          $ANDROID_HOME/platform-tools/adb shell "/data/local/tmp/frida-server &" &
          $ANDROID_HOME/platform-tools/adb forward tcp:10020 tcp:10020
          sleep 5

      - name: Run Frida agent
        run: |
          cd apple-music-alac-downloader
          nohup frida -U -l agent.js -f com.apple.android.music > frida.log 2>&1 &
          sleep 15
          if ! frida-ps -U | grep -q "com.apple.android.music"; then
            echo "::error::Frida injection failed!"
            cat frida.log
            exit 1
          fi

      - name: Execute download
        run: |
          cd apple-music-alac-downloader
          if [ -n "${{ github.event.inputs.album_url }}" ]; then
            ALBUM_URL="${{ github.event.inputs.album_url }}"
          elif [ -n "${{ secrets.DOWNLOAD_URL }}" ]; then
            ALBUM_URL="${{ secrets.DOWNLOAD_URL }}"
          else
            echo "::error::No album URL provided!"
            exit 1
          fi
          
          CLEAN_URL=$(echo "$ALBUM_URL" | sed -E 's|(https?://[^/]+/).*/(album|playlist)/[^/]+/([0-9]+).*|\1\2/\3|')
          echo "Downloading album: $CLEAN_URL"
          
          timeout 1800 go run main.go "$CLEAN_URL" || {
            echo "::warning::First attempt failed, retrying..."
            pkill -f "frida.*android.music"
            nohup frida -U -l agent.js -f com.apple.android.music > frida.log 2>&1 &
            sleep 15
            timeout 1800 go run main.go "$CLEAN_URL"
          }

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: apple-music-alac
          path: apple-music-alac-downloader/downloads/
          retention-days: 7

      - name: Cleanup emulator
        if: always()
        run: |
          $ANDROID_HOME/platform-tools/adb emu kill
          pkill -f "frida-server" || true
